[package]
name = "analyze-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.20"
syn = { version = "2.0.27", features = ["extra-traits"] }
proc-macro2 = "1.0.49"

[lib]
proc-macro = true
